### ISSUE TITLE
how to use in win32 and qt5.15

### ISSUE THREAD

**Issue by hiwjy** [g-rin/qtsnmpclient#3]

**Comment by g-rin** [comment]
Hello @hiwjy.

Short answer is - as in Linux and Qt 5.7 =)
I'll prepare a little example for you in next day or two.

You'll have to:

* create and instance of QtSnmpClient.
* connect to its signals like that:
```
    connect( m_snmp, &QtSnmpClient::responseReceived, this, &MyClass::onResponseReceived );
    connect( m_snmp, &QtSnmpClient::requestFailed, this, &MyClass::onRequestFailed );
```
* set snmp-agent address like that: `m_snmp->setAgentAddress( addr );`
* send a request like that: 
```
        const QByteArray system_oid( ".1.3.6.1.2.1.1" );
        const QByteArray system_desc_oid = system_oid + ".1.0";
        const QByteArray system_name_oid = system_oid + ".5.0";
        const QByteArray system_location_oid = system_oid + ".6.0";
        const QByteArray system_contact_oid = system_oid + ".4.0";
        const QByteArray system_up_time_oid = system_oid + ".3.0";
        m_snmp->requestValues( {
            system_up_time_oid,
            system_desc_oid,
            system_name_oid,
            system_location_oid,
            system_contact_oid } );
```

A response or an error you will receive via the client's signals

**Comment by g-rin** [comment]
Please, keep in mind that the client uses 'public' community and SNMP version v2c (fully compatible with v1 and v2) by default.
Currently it doesn't support SNMPv3.

**Comment by hiwjy** [comment]
thanks i will try tonight with your mind
